export const shopItems = [
  {
    id: 1,
    title: 'Сир "Голландський"',
    img: "img/gollandskiy.jpg",
    price: "34 грн.",
    link: "gollandsky.html",
    kategory: "cheese",
  },
  {
    id: 2,
    title: 'Сир "Качетта на топленому молоці"',
    img: "img/kachetta-milk.jpg",
    price: "49.5 грн.",
    link: "kachetta-milk.html",
    kategory: "cheese",
  },
  {
    id: 3,
    title: 'Масло "Селянське"',
    img: "img/butter-cristian.jpg",
    price: "38 грн.",
    link: "maslo-krestian.html",
    kategory: "butter",
  },
  {
    id: 4,
    title: 'Масло "Топлене"',
    img: "img/butter-toplenoe.jpg",
    price: "34 грн.",
    link: "maslo-toplenoe.html",
    kategory: "butter",
  },
  {
    id: 5,
    title: 'Масло "Шоколадне"',
    img: "img/choko-butter.jpg",
    price: "105 грн.",
    link: "maslo-choko.html",
    kategory: "butter",
  },
  {
    id: 6,
    title: "Сир Сулугуні",
    img: "img/suluguni.jpg",
    price: "34 грн.",
    link: "suluguni.html",
    kategory: "butter",
  },
  {
    id: 7,
    title: "Сир Фета з прованськими травами",
    img: "img/pheto.jpg",
    price: "33 грн.",
    link: "pheto.html",
    kategory: "cheese",
  },
  {
    id: 8,
    title: "Сир Український",
    img: "img/ukranian.jpg",
    price: "34 грн.",
    link: "ukranian.html",
    kategory: "cheese",
  },
  {
    id: 9,
    title: "Масло любительське літнє",
    img: "img/butter-summer.jpg",
    price: "138 грн.",
    link: "maslo-summer.html",
    kategory: "butter",
  },
  {
    id: 10,
    title: "Сирна сіль",
    img: "img/cheese-salt.jpg",
    price: "85 грн.",
    link: "cheese-salt.html",
    kategory: "condiments",
  },
];
