export const shopItems = [
  {
    id: 1,
    title: 'Сыр "Голландский"',
    img: "img/gollandskiy.jpg",
    price: "33 грн.",
    link: "gollandsky.html",
    kategory: "cheese",
  },
  {
    id: 2,
    title: 'Сыр "Качетта на топленом молоке"',
    img: "img/kachetta-milk.jpg",
    price: "48.5 грн.",
    link: "kachetta-milk.html",
    kategory: "cheese",
  },
  {
    id: 3,
    title: 'Масло "Крестьянское"',
    img: "img/butter-cristian.jpg",
    price: "37 грн.",
    link: "maslo-krestian.html",
    kategory: "butter",
  },
  {
    id: 4,
    title: 'Масло "Топленое"',
    img: "img/butter-toplenoe.jpg",
    price: "33 грн.",
    link: "maslo-toplenoe.html",
    kategory: "butter",
  },
  {
    id: 5,
    title: 'Масло "Шоколадное"',
    img: "img/choko-butter.jpg",
    price: "98 грн.",
    link: "maslo-choko.html",
    kategory: "butter",
  },
  {
    id: 6,
    title: "Сыр сулугуни",
    img: "img/suluguni.jpg",
    price: "33 грн.",
    link: "suluguni.html",
    kategory: "butter",
  },
  {
    id: 7,
    title: "Сыр Фета с прованскими травами",
    img: "img/pheto.jpg",
    price: "32 грн.",
    link: "pheto.html",
    kategory: "cheese",
  },
  {
    id: 8,
    title: "Сыр Украинский",
    img: "img/ukranian.jpg",
    price: "33 грн.",
    link: "ukranian.html",
    kategory: "cheese",
  },
  {
    id: 9,
    title: "Масло Традиционное летнее",
    img: "img/butter-summer.jpg",
    price: "115 грн.",
    link: "maslo-summer.html",
    kategory: "butter",
  },
  {
    id: 10,
    title: "Сырная соль",
    img: "img/cheese-salt.jpg",
    price: "80 грн.",
    link: "cheese-salt.html",
    kategory: "condiments",
  },
];
